/*
* Copyright (c)
* All rights reserved.
*/


/*************************Wranning & Error Type**************************************/


#ifndef _ERROR_CODE_H_
#define _ERROR_CODE_H_

#include "xr.h"

#define XR_DEV 			(0x1000<<16)//0x1fff  #define XR_DEV 0x1000 - 0x10FF

#define DEF_LEVEL_1		(0x01<<13)//0x0100
#define DEF_LEVEL_2		(0x02<<13)
#define DEF_LEVEL_3		(0x03<<13)
#define DEF_LEVEL_4		(0x04<<13)
#define DEF_LEVEL_5		(0x05<<13)
#define DEF_LEVEL_6		(0x06<<13)
#define DEF_LEVEL_7		(0x07<<13)


#define DEF_BOARD_FAILED_CLASS					 (XR_DEV|XR_F | (XR_WINF<<29))
#define DEF_BOARD_NORMAL_CLASS				   	 (XR_DEV|XR_S | (XR_GINF<<29))

#define DEF_BOARD_SUCCESS_CLASS					 (DEF_BOARD_NORMAL_CLASS|0x1000)	
#define DEF_BOARD_UPDATE_SUCCESS				 (DEF_BOARD_SUCCESS_CLASS+0x01)	//升级成功


//#define DEF_VOARD_DETECT_CLASS					 (DEF_BOARD_NORMAL_CLASS|0x1010)					//音视频检测信息
//#define DEF_VOARD_DETECT_VIDEO_NOSIGNAL_1		 (DEF_VOARD_DETECT_CLASS+0x01)	//第一路无视频信号
//#define DEF_VOARD_DETECT_VIDEO_NOSIGNAL_2		 (DEF_VOARD_DETECT_VIDEO_NOSIGNAL_1+0x01)	//第二路无视频信号
//#define DEF_VOARD_DETECT_VIDEO_NOSIGNAL_3		 (DEF_VOARD_DETECT_VIDEO_NOSIGNAL_2+0x01)	//第三路无视频信号
//#define DEF_VOARD_DETECT_VIDEO_NOSIGNAL_4		 (DEF_VOARD_DETECT_VIDEO_NOSIGNAL_3+0x01)	//第四路无视频信号

#define DEF_BOARD_STATUS_MASK					 0xFFFFF800
#define DEF_BOARD_STATUS_CLASS					 (DEF_BOARD_NORMAL_CLASS|0x1800)
#define DEF_VOARD_DETECT_VIDEO_NOSIGNAL_1		 (DEF_BOARD_STATUS_CLASS+0x01)	//第一路无视频信号
#define DEF_VOARD_DETECT_VIDEO_NOSIGNAL_2		 (DEF_BOARD_STATUS_CLASS+0x02)	//第二路无视频信号
#define DEF_VOARD_DETECT_VIDEO_NOSIGNAL_3		 (DEF_BOARD_STATUS_CLASS+0x04)	//第三路无视频信号
#define DEF_VOARD_DETECT_VIDEO_NOSIGNAL_4		 (DEF_BOARD_STATUS_CLASS+0x08)	//第四路无视频信号

#define DEF_BOARD_UPDATING						 (DEF_BOARD_STATUS_CLASS+0x10)//0x0002//系统升级中



#define DEF_BOARD_SYSTEM_CLASS			  		 (DEF_BOARD_FAILED_CLASS|0x0000)					//系统信息
#define	DEF_BOARD_POINTER_IS_NULL				 (DEF_BOARD_SYSTEM_CLASS+0x01)	//指针为空
#define	DEF_BOARD_MEMORY_NOT_ENOUGH				 (DEF_BOARD_SYSTEM_CLASS+0x02)	//内存不足
#define	DEF_BOARD_UPDATE_FAILED					 (DEF_BOARD_SYSTEM_CLASS+0x03)	//升级失败

#define	DEF_BOARD_SOCKET_CLASS					 (DEF_BOARD_FAILED_CLASS|0x0010)					// "网络信息"
#define	DEF_BOARD_SOCKET_CONNECT_TIMEOUT		 (DEF_BOARD_SOCKET_CLASS+0x01)	// "TCP连接超时"},
#define	DEF_BOARD_SOCKET_RECV_TIMEOUT			 (DEF_BOARD_SOCKET_CLASS+0x02)	// "接收超时"},
#define	DEF_BOARD_SOCKET_RECV_ERROR				 (DEF_BOARD_SOCKET_CLASS+0x03)	// "接收错误"},
#define	DEF_BOARD_SOCKET_SEND_TIMEOUT			 (DEF_BOARD_SOCKET_CLASS+0x04)	// "发送超时"},
#define	DEF_BOARD_SOCKET_SEND_ERROR				 (DEF_BOARD_SOCKET_CLASS+0x05)	// "发送错误"},
#define DEF_BOARD_HEAD_PACKAGE_LAWLESS			 (DEF_BOARD_SOCKET_CLASS+0x06)	// "数据包头非法"

#define	DEF_BOARD_XML_INCORRECT_FORMAT			 (DEF_BOARD_FAILED_CLASS|0x0020)					// "XML内容格式不正确"
#define DEF_BOARD_XML_SOFTWARE_VGA				 (DEF_BOARD_XML_INCORRECT_FORMAT+0x01)			//VGA
#define DEF_BOARD_XML_SOFTWARE_CVBS				 (DEF_BOARD_XML_INCORRECT_FORMAT+0x02)			//CVBS

#define DEF_BOARD_VIDEO_REGISTER_ERROR			 (DEF_BOARD_XML_INCORRECT_FORMAT+0x03)			//视频编码类型不支持
//

#endif

